sudo: required
services:
  - docker

before_install:
  - docker build -t charanreddy2646/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true charanreddy2646/react-test npm test

after_success:
  - docker build -t charanreddy2646/multi-client ./client
  - docker build -t charanreddy2646/multi-nginx ./nginx
  - docker build -t charanreddy2646/multi-server ./server
  - docker build -t charanreddy2646/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push charanreddy2646/multi-client
  - docker push charanreddy2646/multi-nginx
  - docker push charanreddy2646/multi-server
  - docker push charanreddy2646/multi-worker

